### ISSUE TITLE
SerializeError: unsupported serialized class: OpenOPC.OPCError

### ISSUE THREAD

**Issue by 2makeitwork** [Alexhll/OpenOPC-python3.6#3]
Unfortunately, i can't get it working after making step 9. The service can start but when executing the python file i have the error: (win10, python 3.6.6, working in open mode (not dcom))

o.connect('localhost')
Traceback (most recent call last):

File "", line 1, in
o.connect('localhost')

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\core.py", line 186, in call
return self.__send(self.__name, args, kwargs)

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\core.py", line 461, in _pyroInvoke
data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\util.py", line 170, in deserializeData
return self.loads(data)

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\util.py", line 558, in loads
return self.recreate_classes(serpent.loads(data))

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\util.py", line 411, in recreate_classes
return self.dict_to_class(literal)

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\util.py", line 575, in dict_to_class
return super(SerpentSerializer, cls).dict_to_class(data)

File "C:\Users\PC\Anaconda3\lib\site-packages\Pyro4\util.py", line 390, in dict_to_class
raise errors.SerializeError("unsupported serialized class: " + classname)

SerializeError: unsupported serialized class: OpenOPC.OPCError

I made it work with Python 2.7 (in open mode) but I can't make it work in Python 3.6. The OPC server, OPC server configuration and environment variables are exactly the same (all in open mode). Even the python code are the same. I also tried to install python3 directly (without using the Anaconda environment with the same result) 

>>> o.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\core.py", line 186, in __call__
    return self.__send(self.__name, args, kwargs)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\core.py", line 461, in _pyroInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.FLAGS_COMPRESSED)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\util.py", line 170, in deserializeData
    return self.loads(data)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\util.py", line 558, in loads
    return self.recreate_classes(serpent.loads(data))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\util.py", line 411, in recreate_classes
    return self.dict_to_class(literal)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\util.py", line 575, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\Pyro4\util.py", line 390, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro4.errors.SerializeError: unsupported serialized class: OpenOPC.OPCError

Any clues?

Pyro4                              4.61 (also tried 4.75, and many version in between but same result)
OpenOPC-Python3x       1.2.2 (also tried 1.2.1)
serpent                           1.27
python                            3.6.6
using open mode.

**Comment by HaHaRun000** [comment]
I get the same error based on Python3.6 and Win7 64bit .Hope get the answer. Thank you.

**Comment by Diogo-Ferreira** [comment]
Any updates on this ? I have the same issue

**Comment by Saleem344** [comment]
Any updates on this ? I have the same issue

**Comment by zplorer52** [comment]
Win7 sp1 64bit, Python 3.7.0 32bit, Pyro4==4.82.

> C:\OpenOPC37\bin>OpenOPCService.exe debug
> Debugging service zzzOpenOPCService - press Ctrl+C to stop.
> Info 0x400000FF -
> 
> Starting service on port 7766

**OpenOPCService in Debug mode does Fine**

But [zzzOpenOPCService] as Windows Service throws "unsupported serialized class: OpenOPC.OPCError".
